[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "psutil>=6.1.1",
    "python-telegram-bot==20.7",
    "streamlit>=1.41.1",
]
